sudo: required
services:
  - docker
before_install:
  - docker pull node:8-onbuild
install:
  - docker build -t probot-hello .
script:
  - docker run --rm probot-hello npm run test
  - docker run --rm probot-hello npm run lint
deploy:
  provider: heroku
  api_key: 959ef9a4-04b2-4bb1-9087-c64d629956d2
  on: heroku_production
  app: probot-vic257
